create table usuarios(
    id bigint generated by default as identity,
    nombre varchar(100) not null,
    email varchar(255) not null unique,
    contrasena varchar(255) not null,

    primary key (id)
);