CREATE TABLE respuestas (
    id bigint generated by default as identity,
    mensaje text not null,
    topico_id bigint not null,
    fecha_creacion timestamp not null,
    usuario_id bigint not null ,
    solucion boolean not null default false,

    PRIMARY KEY (id),
    CONSTRAINT fk_respuestas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_respuestas_topico FOREIGN KEY (topico_id) REFERENCES topicos(id)
);